#lang info
(define collection "laicrypto")
(define deps '("base" "crypto-lib"))
(define build-deps '("racket-doc" "scribble-lib" "rackunit-lib"))
(define scribblings '(("scribblings/laicrypto.scrbl" ())))
(define pkg-desc "Lemniscate-AGM Isogeny (LAI) Cryptography: Post-Quantum Secure Encryption")
(define version "1.0")
(define pkg-authors '("GALIH RIDHO UTOMO"))
(define license 'MIT)
(define test-omit-paths '("scribblings"))
